### ISSUE TITLE
Unable to close editing box on Wordpress 4.9

### ISSUE THREAD

**Issue by fatherb** [Enclavely/tailor#159]
I realise this has been discontinued but maybe someone can help to figure out what is going wrong with Wordpress 4.9, which included customizer updates. It would appear whatever they did now interferes with the editing functions in Tailor.

Pushing 'Apply' or the X button in the editing box of Tailor greys out the box and makes any more editing impossible (screenshot below).

![screenshot 2017-11-17 17 47 10](https://user-images.githubusercontent.com/4437677/32961213-8f7c6024-cbbf-11e7-950e-b271f7237809.png)

**Comment by qoalu** [comment]
what is discontinued?

**Comment by richardtape** [comment]
@qoalu 

https://www.tailorwp.com/discontinued/

**Comment by qoalu** [comment]
yeah, just found this in the blog a moment ago. I am aghast as we are in the process of moving our whole website from VC to Tailor and I love the editor. The best out there. I hope some people from the community will step forward and help out. I would definitely be in as I was already contemplating about contributing.

Coming back to the topic, I have the same issue. I will try to look in the code during the weekend.

**Comment by reefki** [comment]
I think it's because some recent changes in `color-picker.js` https://github.com/WordPress/WordPress/commit/b43ddef0bccb41c00dbed9049a0cb54c5b725383#diff-9c3519f4870fac83dc0dbf18cb6bd4c4

Tailor is the best page builder ever and it's sad to hear it has been discontinued. I hope that @andrew-worsfold will do something to save his masterpiece.

#SaveTailor

**Comment by reefki** [comment]
Tried to update color alpha script with the newest version https://github.com/kallookoo/wp-color-picker-alpha but it looks like the alpha slider doesn't show up.

![screen shot 2017-11-20 at 19 56 53](https://user-images.githubusercontent.com/10998084/33019538-5daaec26-ce2d-11e7-9ef6-bb82c1fdc361.png)

**Comment by reefki** [comment]
After some digging I got it to work:

![screen shot 2017-11-20 at 20 15 43](https://user-images.githubusercontent.com/10998084/33020138-abb35f8c-ce2f-11e7-8ee9-171218a09711.png)

If you want to try it out you can replace `tailor/assets/js/dist/sidebar.js` with https://gist.github.com/reefki/d4addff26bef3877b58dd572276dc80e and turn on script debugging by placing `define('SCRIPT_DEBUG', true);` into your `wp-config.php`.

**Comment by fatherb** [comment]
Hi - I downloaded sidebar.js from your gist.github, placed it in tailor/assets/js/dist/ and ran npm install - then made a zip file of the tailor folder. Then deactivated and deleted Tailor from Wordpress and uploaded the new zip file. I'm still seeing the same problems with not being able to close the editing box.

I think there are errors in the new sidebar.js file - is that possible? The plugin editor says line 1 is a problem.

**Comment by reefki** [comment]
No need to run `npm install` just replace the `tailor/assets/js/dist/sidebar.js`, also no need to deactivate and re-upload the plugin you can directly replace the file using FTP client. Don't forget to enable `SCRIPT_DEBUG` as I stated above in order to make WordPress loads `sidebar.js` instead of `sidebar.min.js`.

**Comment by fatherb** [comment]
Thanks. Tested and confirmed working. Editing box issue has gone. Well done! 
I think you should submit an update request to have this included. Otherwise do we have to branch it and put it in the wordpress plugins repository as a new plugin? I don't really understand how github works...

**Comment by reefki** [comment]
@fatherb I still have a pull request pending that makes me doubt they will even consider merging my pulls.

I would rather wait for @andrew-worsfold decision, we all know he doesn't have enough spare time to focus on maintaining it, but I believe he doesn't pleased to see something that he created from the ground with so many efforts and times leave abandoned at least we hope he will do something to make it work on WP 4.9.

Otherwise, let's hope someone will jump in to take control of this repository.

**Comment by arashohadi** [comment]
Here's @reefki's fix minified (```sidebar.min.js```). Just tried it on one of my sites and it worked. This way you don't have to change ```SCRIPT_DEBUG```.

https://gist.github.com/arashohadi/f0cfa6464ad12d0b8c6bc6d4ea526dd7

**Comment by arashohadi** [comment]
@reefki Is it possible to make your changes in assets/js/src folder? There is a colorpicker.js in that folder for instance. I could help with the compilation and minification after that. I would do it myself but I don't know what you have changed :)

**Comment by reefki** [comment]
@arashohadi I have another modified version on my local machine and yes I modified it from `src` folder then compile them. But still not final because when you click on any of color in palette list the value in text field becomes empty.

**Comment by arashohadi** [comment]
@reefki Ok thanks, please keep the rest of us updated if you manage to solve it. Thanks!
